Repository Proteus-Eretes/mijn-proteus, pull requests merged in 2022-11, with the labels that each got.

#10 Generate prisma client before building in Docker
  Dockerfile
Labels: 🐛 Bug, 🗄️ Database

#7 Add material server API
  .eslintrc.json
  .prettierrc
  logic/index.ts
  logic/material.ts
  logic/materialType.ts
  package.json
  prisma/migrations/20221107130827_material/migration.sql
  prisma/schema.prisma
  prisma/seed/index.ts
  prisma/seed/material.ts
  prisma/seed/materialType.ts
  prisma/seed/quote.ts
  prisma/seed/testdata/material.json
  prisma/seed/testdata/materialType.json
  prisma/seeding.ts
  server/api/material/index.get.ts
  server/api/material/index.post.ts
  server/api/material/type/index.get.ts
  server/api/material/type/index.post.ts
  server/api/quote/index.post.ts
  server/utils/index.ts
  server/validation.ts
  tailwind.config.js
Labels: ✨ Enhancement, 📡 Backend, 🗄️ Database

#13 Add better error handling
  composables/useApiError.ts
  server/api/[...].ts
  server/api/[...notfound].ts
  server/error.ts
  server/logic/index.ts
  server/logic/material.ts
  server/logic/materialType.ts
  server/plugins/apiError.ts
  server/utils/index.ts
Labels: ✨ Enhancement, 📡 Backend

#15 Fix module resolution issues
  composables/useApiError.ts
  package.json
  server/plugins/apiError.ts
Labels: 🐛 Bug, ⏫ Dependencies

#14 Add basic default page layout
  .eslintrc.json
  assets/logo/external-color.png
  assets/logo/internal-color.png
  components/NavBar.vue
  components/NavBar/MenuLarge.vue
  components/NavBar/MenuSmall.vue
  components/NavBar/NavBar.vue
  components/NavBar/Search.vue
  layouts/default.vue
  nuxt.config.ts
  package.json
  pages/404.vue
  pages/index.vue
  tailwind.config.js
Labels: ✨ Enhancement, 🖥️ Frontend

#8 Migrate ledensysteem over to mijn-proteus
  README.md
  components/NavBar/NavBar.vue
  package.json
  server/api/contacts/[id]/index.delete.ts
  server/api/contacts/[id]/index.patch.ts
  server/api/contacts/index.post.ts
  server/api/groups/[id]/index.delete.ts
  server/api/groups/[id]/index.get.ts
  server/api/groups/[id]/index.patch.ts
  server/api/groups/index.post.ts
  server/api/groups/memberships/[id]/index.delete.ts
  server/api/groups/memberships/[id]/index.patch.ts
  server/api/groups/memberships/index.post.ts
  server/api/health.ts
  server/api/members/[id]/index.delete.ts
  server/api/members/[id]/index.get.ts
  server/api/members/[id]/index.patch.ts
  server/api/members/index.post.ts
  server/api/studies/[id]/index.delete.ts
  server/api/studies/[id]/index.patch.ts
  server/api/studies/index.post.ts
  server/api/studies/options/[id]/index.delete.ts
  server/api/studies/options/[id]/index.patch.ts
  server/api/studies/options/index.get.ts
  server/api/studies/options/index.post.ts
  server/logic/contact.ts
  server/logic/database.ts
  server/logic/group.ts
  server/logic/index.ts
  server/logic/material.ts
  server/logic/materialType.ts
  server/logic/member.ts
  server/logic/membership.ts
  server/logic/quote.ts
  server/logic/study.ts
  server/prisma/client.ts
  server/prisma/migrations/20221115171551_ledensysteem/migration.sql
  server/prisma/schema.prisma
  server/prisma/seed/group.ts
  server/prisma/seed/index.ts
  server/prisma/seed/member.ts
  server/prisma/seed/study.ts
  server/prisma/seed/testdata/group.json
  server/prisma/seed/testdata/member.json
  server/validation.ts
Labels: ✨ Enhancement, 📡 Backend, 🗄️ Database

#19 Add basic datastore level constraints
  server/api/groups/[id]/index.patch.ts
  server/api/groups/index.post.ts
  server/logic/contact.ts
  server/logic/group.ts
  server/logic/member.ts
  server/logic/membership.ts
  server/logic/study.ts
  server/plugins/apiError.ts
  server/plugins/constraints.ts
  server/prisma/client.ts
  server/prisma/constraints.ts
  server/prisma/migrations/20221121003002_groupconstraint/migration.sql
  server/prisma/schema.prisma
  server/prisma/seed/group.ts
  server/prisma/seed/index.ts
  server/prisma/seed/member.ts
  server/prisma/seed/testdata/group.json
  server/prisma/seed/testdata/member.json
Labels: 🗄️ Database

#16 Add UI for material endpoints
  components/Alert.vue
  components/Button.vue
  components/Card.vue
  components/Input/Select.vue
  components/Input/Text.vue
  components/NavBar/NavBar.vue
  components/NavBar/Search.vue
  components/Page/Material/TypesCreate.vue
  components/TwoColumn.vue
  composables/apiErrorHandler.ts
  composables/sendApiReq.ts
  composables/toApiError.ts
  composables/useApiError.ts
  layouts/default.vue
  package.json
  pages/material.vue
  pages/material/index.vue
  pages/material/types.vue
  server/api/material/index.get.ts
  server/api/material/index.post.ts
  server/api/material/type/index.get.ts
  server/api/material/type/index.post.ts
  server/error.ts
  server/logic/material.ts
  server/logic/materialType.ts
  server/plugins/apiError.ts
  server/utils/index.ts
  tsconfig.json
Labels: ✨ Enhancement, 🖥️ Frontend

#29 chore(ci): disable running linting actions on a push event
  .github/workflows/linting.yml
Labels: ✨ Enhancement, github_actions

#27 fix(docker): add composables folder
  Dockerfile
Labels: 🐛 Bug
